server:
  port: 8080

# DataSource Setting + JPA Setting + Redis
spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/login?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: root
  redis:
    host: localhost
    port: 6379

# JWT
jwt:
  secret : VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHN
