server:
  port: 8080

# DataSource Setting + JPA Setting + Redis
spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/login?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
  # smtp
  mail:
    host: smtp.gmail.com
    port: 587
    username: dnejdzlr2@gmail.com
    password: qmnioerwgofnlofa
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
#          ssl:
#            enable: false #google이나 naver의 SMTP를 사용할 때에는 해당 값을 true로 한 후, spring.mail.username과 spring.mail.password를 작성하셔서 사용해야 합니다.

# JWT
jwt:
  secret : VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHN
